module.exports = {
    apps: [
        {
            name: "estafee-backend",
            script: "./apps/backend/dist/main.js",
            cwd: "/var/www/estafee/estafee-monorepo",
            instances: 1,
            exec_mode: "fork",
            env: {
                NODE_ENV: "production",
                PORT: 3001,
            },
            env_production: {
                NODE_ENV: "production",
                PORT: 3001,
            },
            error_file: "./logs/backend-error.log",
            out_file: "./logs/backend-out.log",
            log_file: "./logs/backend-combined.log",
            time: true,
            autorestart: true,
            max_restarts: 10,
            min_uptime: "10s",
            max_memory_restart: "500M",
        },
        {
            name: "estafee-frontend",
            script: "node_modules/next/dist/bin/next",
            args: "start",
            cwd: "/var/www/estafee/estafee-monorepo/apps/frontend",
            instances: 1,
            exec_mode: "fork",
            env: {
                NODE_ENV: "production",
                PORT: 3000,
            },
            env_production: {
                NODE_ENV: "production",
                PORT: 3000,
            },
            error_file: "./logs/frontend-error.log",
            out_file: "./logs/frontend-out.log",
            log_file: "./logs/frontend-combined.log",
            time: true,
            autorestart: true,
            max_restarts: 10,
            min_uptime: "10s",
            max_memory_restart: "1G",
        },
    ],
};
